### PR TITLE
DNS migration

### PR DESCRIPTION
**Pull request by opadron**
- Updates the `spack.io` and `packages.spack.io` services to run in their own namespace, `spack`, instead of the `default` namespace.
- Modifies all the new manifests to expect ingress via `spack.io` with `next.spack.io` fallback.
   - Includes a number of custom "stopgap" ingresses to supplement those automatically created by helm charts.
- Modifies the gitlab service subdomains to more clearly distinguish it from other subdomains:
   - `minio.spack.io` -> `minio.gitlab.spack.io`
   - `registry.spack.io` -> `registry.gitlab.spack.io`
- Migrates the `auto-updater` cronjobs to `spack.io`, `spack-packages`, and `cdash` services.

### Migration Deployment Checklist

- [x] Update the old DNS records to point to the new elastic load balancers.
   - Must wait for DNS changes to propagate (could take effect immediately; could take up to 15 minutes, depends on AWS).
   - The services on the old cluster would no longer be accessible through DNS.
- [x] Deploy the changes in this PR (This must be done *after* DNS changes propagate)
- [x] Iterate/troubleshoot.
- [ ] Once the changes have been confirmed working, we can merge this PR and push one more update to `production`.

Throughout the above process, the services on the old infrastructure will not be available, and service to the new infrastructure is likely to be disrupted.  The amount of time needed to return the new infrastructure to service will depend on how many problems we encounter with the changes in this PR.

### Migration Post-Deployment Checklist
At this point, the new infrastructure will be serving traffic over the original `spack.io` domain *as well as* the temporary `next.spack.io` subdomain.

- [ ] Shut down and terminate all AWS resources on the Kitware account, except for the Route53 hosted zone.
- [ ] Monitor services to ensure proper operation/audit any places in code and/or configuration where references to `next.spack.io` will need to be updated to `spack.io`.
   - We can take as much time here as we'd like until we're satisfied that everything is working as expected and that we've properly updated all references to the original domain.
- [ ] Remove DNS entries for `next.spack.io`.
- [ ] Remove stopgap ingresses and related configurations.  (This will be done in a follow-up PR)
- [ ] Transfer Route53 zone to the new LLNL account.
- [ ] Shut down and terminate any remaining services or resources on the Kitware account.
   - At this point, we can repurpose the Kitware account or decommission it entirely.

Please weigh in and let me know if you think this is a good plan.

### CODE REVIEW

**Comment by opadron** [comment]
There are still some AWS resources that I haven't yet removed from the Kitware account.  These are:

 - Eight (8) S3 Buckets:
 
Name | AWS Region | Access | Creation date
-- | -- | -- | --
cf-templates-fmeo7n9fklp-us-east-1 | US East (N. Virginia) us-east-1 | Objects can be public | July 17, 2019, 17:07:39 (UTC-04:00)
spack-mirrors | US East (N. Virginia) us-east-1 | Public | July 14, 2020, 12:46:28 (UTC-04:00)
spack-pr-mirrors | US East (N. Virginia) us-east-1 | Bucket and objects not public | October 7, 2020, 16:30:46 (UTC-04:00)
spack-private | US East (Ohio) us-east-2 | Public | December 5, 2019, 16:43:38 (UTC-05:00)
spack-public | US East (Ohio) us-east-2 | Public | September 21, 2018, 22:27:09 (UTC-04:00)
spack-repros | US East (Ohio) us-east-2 | Public | December 11, 2019, 14:05:25 (UTC-05:00)
spack-tutorial | US East (Ohio) us-east-2 | Public | November 5, 2019, 16:22:19 (UTC-05:00)
spack-tutorial-container | US East (Ohio) us-east-2 | Public | January 27, 2020, 16:05:49 (UTC-05:00)

 - One (1) customer-managed policy (related to S3).
 `SpackPRMirrorAllAccessPolicy - Can perform all actions on the spack-pr-mirrors bucket`

 - Four (4) IAM users.

User name | Groups | Access key age | Password age | Last activity | MFA
-- | -- | -- | -- | -- | --
gamblin2@llnl.gov | None | None | 288 days | Yesterday | Not enabled
omar.padron@kitware.com | None | 1172 days | 1172 days | Today | Not enabled
prmirror | None | 239 days | None | 107 days | Not enabled
spack | None | None | None | 32 days | Not enabled

My primary concern is the S3 buckets.  AWS gives these statistics:

Total storage | Object count | Avg. object size
 -- | -- | --
322.3 GB | 31.3 k | 10.5 MB

What should we do with these buckets?

@tgamblin @zackgalbreath @scottwittenburg

**Comment by zackgalbreath** [comment]
I'll defer to Scott, but my hunch is that they can be safely deleted. If that's too scary we could consider moving their contents to Glacier @ LLNL AWS?

**Comment by opadron** [comment]
#90

**Comment by scottwittenburg** [comment]
> What should we do with these buckets?

Those can be safely deleted.

**Pull request merged**
