### PR TITLE
Remove patched gitlab images, gitops image

### PR DESCRIPTION
**Pull request by mvandenburgh**
Removes a bunch of docker images that are no longer used.

### CODE REVIEW

**Review by AlmightyYakob — APPROVED** [review]

**Comment by AlmightyYakob** [comment]
@mvandenburgh For posterity can you remind us why we switched back to using the stock gitlab images? Was it simply that with the gitlab upgrade, the crafted images were rendered useless?

**Comment by scottwittenburg** [comment]
> why we switched back to using the stock gitlab images?

The images we used before were patched to ignore the max yaml size limit.  Now we are increasing the limit with that cronjob which invokes the rails runner.

**Review by scottwittenburg — APPROVED** [review]
Approving, but only for the removal of the `gitlab-*` docker files.  Hopefully someone else can chime in on the `gitops` files.

**Comment by mvandenburgh** [comment]
> Approving, but only for the removal of the `gitlab-*` docker files. Hopefully someone else can chime in on the `gitops` files.

Maybe @zackgalbreath can confirm. I believe that `gitops` image was a custom thing Omar made related to the old Flux v1 setup with the "staging" gitlab deployment (before we had an entire staging cluster). Either way, it isn't used elsewhere in the repo from what I can tell.

**Comment by zackgalbreath** [comment]
> Maybe @zackgalbreath can confirm. I believe that `gitops` image was a custom thing Omar made related to the old Flux v1 setup with the "staging" gitlab deployment (before we had an entire staging cluster). Either way, it isn't used elsewhere in the repo from what I can tell.

This is correct and it can be safely removed.

**Review by zackgalbreath — APPROVED** [review]

**Pull request merged**
