### PR TITLE
Use service accounts for S3 access in gitlab runners instead of rotating credentials

### PR DESCRIPTION
**Pull request by mvandenburgh**
TODO

Before merging:
- [x] Create `PutAndDeleteObjectsInBucketSpackBinaries` and `PutAndDeleteObjectsInBucketSpackBinariesPRs` IAM roles in AWS

After merging:
- [ ] Remove the `RotateIAMAccessKeysForGitLab` IAM role from AWS
- [ ] Remove the `pull-requests-binary-mirror`, `protected-binary-mirror`, and `develop-binary-mirror` IAM users from AWS

### CODE REVIEW

**Comment by mvandenburgh** [comment]
@zackgalbreath this is now ready for review. I cleaned it up and implemented what we discussed today.

**Comment by mvandenburgh** [comment]
I added the new service accounts in this PR to the cluster (without deleting any of the existing ones) and updated the staging runners to use them instead of the `pipeline/runner` service account (i.e. the one that this PR replaces). I ran a staging pipeline and it was able to successfully write to the binary mirror S3 bucket https://gitlab.staging.spack.io/mvandenburgh/spack-ci/-/pipelines/68

**Comment by danlamanna** [comment]
@mvandenburgh Can this be closed?

**Comment by mvandenburgh** [comment]
Yes.

**Pull request closed without merging**
