### PR TITLE
Remove host path mounted keys

### PR DESCRIPTION
**Pull request by kwryankrattiger**
PCluster AMI does not have the keys, prefer the secrets

### CODE REVIEW

**Review by mvandenburgh — COMMENTED** [review]
:+1:

**Review by scottwittenburg — APPROVED** [review]
Thanks @kwryankrattiger!

**Comment by scottwittenburg** [comment]
I'll keep an eye on these runners to be sure, but I think this should resolve the issue mentioned [here](https://github.com/spack/spack-infrastructure/pull/457/files#r1207083485).

**Comment by scottwittenburg** [comment]
This job just ran on one of these runners, and it appears the keys are present again :tada: 

https://gitlab.spack.io/spack/spack/-/jobs/7142920

Thanks @kwryankrattiger!

**Pull request merged**
