### PR TITLE
Record EC2 instance type for builder pods

### PR DESCRIPTION
**Pull request by zackgalbreath**
Update our OpenSearch records to include the type of instance that a job ran on.

### CODE REVIEW

**Review by mvandenburgh — APPROVED** [review]
It appears that no job has managed to grab pod info since 
#427 was merged yesterday. It seems that the runner pods are disappearing before the taxonomy job runs... but assuming I can get that working, this PR makes sense to me :+1:

**Comment by zackgalbreath** [comment]
> It appears that no job has managed to grab pod info since #427 was merged yesterday. It seems that the runner pods are disappearing before the taxonomy job runs... but assuming I can get that working, this PR makes sense to me 👍

I was worried about that, but thanks for digging into it & letting us know. In the meantime I'll ponder alternate strategies to grab this info while it's available.

**Comment by AlmightyYakob** [comment]
Any update on this?

**Comment by mvandenburgh** [comment]
> It appears that no job has managed to grab pod info since #427 was merged yesterday. It seems that the runner pods are disappearing before the taxonomy job runs... but assuming I can get that working, this PR makes sense to me +1

I haven't revisited #427, so this is still the current status quo ^

**Pull request closed without merging**
