### PR TITLE
Add GitLab + GitLab Runner to dev environment

### PR DESCRIPTION
**Pull request by mvandenburgh**
Adds GitLab and a runner as services to the local docker-compose development configuration. This should drastically improve the ability to test things related to the Django app locally.

### CODE REVIEW

**Comment by jjnesbitt** [comment]
Should we update the `GITLAB_TOKEN` and `GITLAB_ENDPOINT` values in the `analytics/dev/.env.docker-compose*` files?

**Comment by mvandenburgh** [comment]
> Should we update the `GITLAB_TOKEN` and `GITLAB_ENDPOINT` values in the `analytics/dev/.env.docker-compose*` files?

Added.

**Comment by danlamanna** [comment]
Unfortunately this is mostly unusable on macOS since it uses QEMU to emulate ARM (see https://github.com/sameersbn/docker-gitlab/pull/2803). I cancelled the init script after 10-15 minutes waiting for it to succeed.

**Comment by danlamanna** [comment]
I pused a small change to use a Docker image that's being built for both amd64 and arm64. This works well for me now.

**Review by danlamanna — APPROVED** [review]

**Pull request merged**
