### PR TITLE
Update Production

### PR DESCRIPTION
**Pull request by opadron**
Depends on #212

### CODE REVIEW

**Comment by kotfic** [comment]
This LGTM -  though I can't speak on the spack-bot update.  Who is responsible there?

**Review by kotfic — APPROVED** [review]

**Comment by scottwittenburg** [comment]
Although @tgamblin approved the PR updating spackbot deployment before the spackbot PR was merged, I wasn't going to merge it to `main` until the spackbot work was final.  However it appears @opadron saw the approval and merged it.  It shouldn't go into production though or spackbot won't work anymore.

**Review by scottwittenburg — CHANGES_REQUESTED** [review]
Not sure how to handle the commit updating the spackbot deployment, maybe that should be reverted from `main`?  At any rate, it shouldn't be merged to `production`.

**Comment by opadron** [comment]
@scottwittenburg PTAL

**Review by scottwittenburg — APPROVED** [review]

**Pull request merged**
