### PR TITLE
Add "do-not-evict" annotation to GitLab runner manager pods

### PR DESCRIPTION
**Pull request by zackgalbreath**

### CODE REVIEW

**Comment by zackgalbreath** [comment]
I made sure this was the right place to add this setting my manually editing & applying the x86_64 testing YAML file. I verified that I saw the annotation show up as expected before flux overwrote my changes.

**Review by AlmightyYakob — COMMENTED** [review]
Should we also include the test runners?

**Comment by zackgalbreath** [comment]
> Should we also include the test runners?

I dunno, what do you think? I left them out on purpose so they don't cost us more money than necessary, but maybe it's worth the surcharge for a more faithful reproducer of our production runners.

**Comment by AlmightyYakob** [comment]
> > Should we also include the test runners?
> 
> I dunno, what do you think? I left them out on purpose so they don't cost us more money than necessary, but maybe it's worth the surcharge for a more faithful reproducer of our production runners.

I doubt cost will really be an issue, afaik they're barely ever used anyway. I was mainly concerned with reproducibility.

**Review by AlmightyYakob — APPROVED** [review]

**Pull request merged**
