### PR TITLE
Upgrade GitLab to 13.8.7

### PR DESCRIPTION
**Pull request by zackgalbreath**

### CODE REVIEW

**Comment by tgamblin** [comment]
@zackgalbreath looks like it was pretty easy -- is this it?

**Comment by scottwittenburg** [comment]
> @zackgalbreath looks like it was pretty easy -- is this it?

Nope that didn't do it.  I forgot we had to use slightly customized gitlab images, so I'm building and pushing those, then I'll make another PR here and see if that's all we need.

**Comment by opadron** [comment]
Hey, just a heads up, this got pushed directly into `production`, instead of to the `llnl` branch.

I understand that the current workflow is a bit of a pain, but please take care to make sure that new infrastructure PRs are made against the `llnl` branch (until I complete the migration).

**Comment by opadron** [comment]
For the record, I ended up merging `production` into `llnl`, and then force-pushing `llnl` back to `production`.  (In case anyone going through the git history is wondering what the heck happened and lands on this PR!)

**Pull request merged**
